version: "3.8"

services:
  nginx:
    container_name: nginx
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql

  php:
    container_name: php
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
      - ./src/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  mysql:
    platform: linux/x86_64
    container_name: mysql
    image: mysql:8
    env_file:
      - ./env/mysql.env

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./env/phpmyadmin.env
    ports:
      - 81:80
